### ISSUE TITLE
Unclaimed string names 

### ISSUE THREAD

**Issue by borasaki** [abarichello/godot-ci#122]
Hey! I'm running into an issue at what seems to be the end of the Web build section, where it ends with 522 unclaimed string names at exit an tosses a 255 error out, would anyone happen to know anything about that?
![Capture](https://github.com/abarichello/godot-ci/assets/102422083/1f9588ff-e9f4-42dc-9aab-61744a864904)

**Comment by Calinou** [comment]
The unclaimed string names error is likely unrelated to the *actual* error you're encountering. Please post the *entire* CI log here.

**Comment by borasaki** [comment]
Here you go, that should be the logs zip file! Sorry for this, I'm quite unfamiliar with GitHub action workflow.
[logs.zip](https://github.com/abarichello/godot-ci/files/13064740/logs.zip)

**Comment by OverloadedOrama** [comment]
This error is because you are using the old Godot 3's command line options. You need to change `godot -v --export "HTML5" ../build/web/index.html`, which is how it used to work in Godot 3, to `godot --headless -v --export-release "HTML5" ../build/web/index.html`. See https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html for more information.

**Comment by borasaki** [comment]
Gotcha, thank you! I'll see if I'm not dumb enough to fix it from here!
