### ISSUE TITLE
Android Release CI fails due to base64: invalid input

### ISSUE THREAD

**Issue by 2shady4u** [aBARICHELLO/godot-ci#40]
Could there be a little bit more information on how to actually encode the release key with base64?

I encoded the keystore key as indicated, but I am unable to recover the key again once it has been encoded.
Using WSL (Ubuntu) I get the following errors messages:
![Capture](https://user-images.githubusercontent.com/42484461/97743653-45284780-1ae6-11eb-91d5-7a7003a40c18.PNG)

It also crashes on the Gitlab runner (evidently):
![image](https://user-images.githubusercontent.com/42484461/97743586-2b870000-1ae6-11eb-929d-d2f195feb8ec.png)

I just took the content of the generated "key" file and copy-pasted it into the Gitlab variables section, but since it doesn't
work on WSL, it also logically won't work on the Godot-CI image....

What am I doing wrong here?
Could there be some more information added to the docs?

**Comment by Calinou** [comment]
That `echo` command should likely be changed to `cat $SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > /root/release.keystore`.

**Comment by 2shady4u** [comment]
ah! will test asap. Can i assume that the original PR had the key stored as a **variable** instead of as a **file** ?

**Comment by 2shady4u** [comment]
@Calinou and @asheraryam Ok, it works when I switch the `echo` to `cat` 👍 
Could this be changed in the YML?

**Comment by asheraryam** [comment]
@2shady4u You guessed correctly, in the original PR had the key stored as a variable in the gitlab settings instead of as a file in the repo.

This is preferable since storing key files in repositories is usually frowned upon, and should not be the default behavior if there is a better alternative.

We shouldn't change the YML to use a file instead of a variable, but we can add better documentation to explain how to add a variable on gitlab. Feel free to open another issue for that.
