### ISSUE TITLE
No CI for the docker images themselves

### ISSUE THREAD

**Issue by neoq** [aBARICHELLO/godot-ci#52]
Hi, first of all, love the existing work.
I was just wondering how the images get to the docker hub. I assume @aBARICHELLO is pushing them manually at the moment because the github and gitlab CI only demonstrate the godot CI. If that is the case I suggest replacing the current CI by jobs that build the godot-ci images and automatically push and tag them on the docker hub for specific branches like `master` or `3.2`. This would ensure that the images on the dockerhub are always in sync with the repository and it would make the image contents more transparent to the users. The godot-ci will still be demonstrated by the existing example repositories.

If desired, I could possibly submit a pull request implementing this as soon as I get to it.

Best regards

**Comment by aBARICHELLO** [comment]
I use Docker Hub's automated builds instead of building them myself. The `latest` tags are triggered manually to prevent new builds over commits that don't change the image itself while the other branches are built automatically.

![image](https://user-images.githubusercontent.com/16687318/114112291-76394f00-98b2-11eb-946e-a0f467270ee0.png)

For example, the current commit for the `latest` tag is 2c4434c since the commit 9213e16 only had README updates, you can actually see the dockercloud badge here:

![image](https://user-images.githubusercontent.com/16687318/114112549-fa8bd200-98b2-11eb-98fe-47fc7f67480f.png)

I hope I made myself clear, let me know if you have any questions.

**Comment by neoq** [comment]
Yeah that clears it up. Thank you. I did not think of Docker Hub's automated builds :)
