### ISSUE TITLE
Update to 3.4

### ISSUE THREAD

**Issue by Calinou** [abarichello/godot-ci#62]
[`3.4-stable` is tagged on GitHub](https://github.com/godotengine/godot/releases/tag/3.4-stable), which means this Docker image can be updated for Godot 3.4 now. (The announcement post will be made today or tomorrow.)

**Comment by mars3142** [comment]
Would it be possible to create a cron job, which build the latest godot-ci without manual doing? That would speed up every new docker container with godot for ci.

**Comment by abarichello** [comment]
The latest releases took longer because I was used to Docker Hub's Autobuild, it got removed from the free plan and now I have to do everything manually.
![image](https://user-images.githubusercontent.com/16687318/140821613-30788c71-13f8-4458-b8dc-9060ffda09f6.png)
I like the idea of a daily script, it would be a cheaper option as a replacement to automate everything

**Comment by abarichello** [comment]
#65

**Comment by OverloadedOrama** [comment]
> I noticed that Mac build is failing with this error
> 
> > ERROR: Cannot export project with preset "Mac OSX" due to configuration errors:
> > Invalid bundle identifier: Identifier is missing.
> 
> See [example 1](https://gitlab.com/barichello/godot-ci/-/jobs/1762058075) and [example 2](https://github.com/crystal-bit/godot-game-template/runs/4203040662?check_suite_focus=true).
> 
> I solved it in godot-game-template ([diff](https://github.com/crystal-bit/godot-game-template/commit/c71054832c6126c5dbf76b2e05759c7136d8f53f#diff-e3dd487a7d10e05fb76d28a6e22a7da4484f558665cd4ceac7583857378b67a2R120-R123)) by manually specifing the identifier in the export preset. Not sure if something is changed with Godot 3.4.

This is most likely due to https://github.com/godotengine/godot/pull/49276/. Mac projects need to have an identifier in order to be valid. Also keep in mind that only letters, numbers, dashes (-) and dots (.) are allowed. If the identifier has, for example, an underscore (_) it will also give an error during export.

**Comment by davcri** [comment]
I noticed that also the Android debug build is now [failing](https://gitlab.com/barichello/godot-ci/-/jobs/1762058078) as already mentioned in #59:
```
ERROR: Cannot export project with preset "Android Debug" due to configuration errors:
A valid Android SDK path is required in Editor Settings.
```

There is a workaround (Dockerfile + Docker Image) here: https://github.com/crystal-bit/godot-game-template/issues/53#issuecomment-968344779
I don't know if it's a good approach, but I if it's helpful I can open a PR to update `godot-ci`'s Dockerfile!

**Comment by Calinou** [comment]
@davcri Android exporting should be fixed in the next image release since https://github.com/abarichello/godot-ci/pull/69 was merged.

**Comment by Calinou** [comment]
Closing, as the engine now offers 3.4 with the Android exporting fix.
